@startuml retail-security-dashboard-app

start

if (direction?) then (ingress)
  fork
    :retail-security-dashboard;
    floating note left: product

  end fork
else (egress)
  :Allow All;
endif

@enduml